### ISSUE TITLE
Unsure if bug? 

### ISSUE THREAD

**Issue by kirinelf** [Aida-Enna/XIVPlugins#7]
Hi there, just wondering about something. In the event that a unique (green item) is already owned, it shows the error and skips it. Is it possible for such cases to be passed as well? 

P.S.: I loved your work on PSO2, although I never ended up playing it very long. Still, all my thanks for the Tweaker!

**Comment by Aida-Enna** [comment]
I'll have to do some testing before I can be sure, but I imagine theoretically it could. I'll take a look!

And awwww, thank you! I'm always happy to help where I can 😄

**Comment by Aida-Enna** [comment]
Just wanted to note that I haven't forgotten about this - It's already implemented in the plugin internally, but I'm work on another system and I'm undergoing extensive testing with it because we're dealing with people's loot and I do not want to mess that up. Once the new version is ready, this option will be in it. Thank you for your patience!

**Comment by kirinelf** [comment]
No worries, waiting patiently!

**Comment by Aida-Enna** [comment]
This feature is now live in the new plugin as part of the auto-loot stuff!
![image](https://user-images.githubusercontent.com/5483362/228289942-2865c4e2-db0d-4d93-ba27-f15c5821f636.png)

Please check it out when you get a chance and let me know if it works as you wanted. 🙏

**Comment by kirinelf** [comment]
Just came back from a mini-hiatus, thanks for implementing this! 

Looks like you've added a new Auto setting, am I right in assuming that this will auto-roll on any and all loot that shows up without input? If I may be so bold, I'd like to further request that the auto-pass option applies even to the manual /need etc. commands, assuming it isn't too difficult! I like to run stuff unsynced and pass if anyone wants stuff like mounts and such even if I don't have them yet, so having it implemented for roulettes with my /need macro but not actually auto-on would be great! 

I'm also seeing some weird glitches when letting the Auto-Loot kick in, such as it somehow Passing on stuff I don't have yet or getting messages saying it couldn't AutoGreed. Have a gander at the below image: 

![ffxiv_dx11_2023-04-02_16-40-06](https://user-images.githubusercontent.com/30263373/229337650-586d8ff1-1cd5-435f-a751-95d72c950853.png)

I don't have either item in my inventory, yet LM apparently passed on one and couldn't auto greed anything else (I have it set to Greed). Opening up the actual Loot thingy (which I forgot to screenshot), it did indeed pass on one and Greeded another, so why it's saying it couldn't Auto Greed, I dunno. 

I also got the following error at one point which I don't understand much, but it showed up right when the loot window showed up but I was transitioning to another screen (Stigma Dreamscape if it helps, right after the first boss when going to the next area), and I haven't seen it since: 

![ffxiv_dx11_2023-04-02_16-08-43](https://user-images.githubusercontent.com/30263373/229337755-286d8048-f34d-4d96-83b5-a96af9e67742.png)

Finally, because of said hiatus, I haven't been running too many duties, so I haven't actually tried to see if it properly skips Unique items. I'll report back if anything weird happens! 

Hope these make sense to you, and sorry for dumping more stuff on your plate!

**Comment by Aida-Enna** [comment]
```Looks like you've added a new Auto setting, am I right in assuming that this will auto-roll on any and all loot that shows up without input? If I may be so bold, I'd like to further request that the auto-pass option applies even to the manual /need etc. commands, assuming it isn't too difficult! I like to run stuff unsynced and pass if anyone wants stuff like mounts and such even if I don't have them yet, so having it implemented for roulettes with my /need macro but not actually auto-on would be great!```

Would it work if I made a /needbutpass command? That way it'll need but also pass but only when you use that command, ignoring the setting in options completely.

As for the image, that's really weird. I'm not sure why it would pass there. Let me know if it happens again or you can discern some sort of pattern - I tested it with myself a few friends for a week or so and didn't get that issue.

As for the scary red error message, it's just a debug message that means it couldn't roll for some reason, or that the number of roles wasn't what it expected. It generally happens when (as you said) you leave an area and it's still trying to roll on something. You can just ignore it, I'll disable it next update.

And no problem, I enjoy the work! I'm just swamped with PSO2 stuff right now so things are a bit slow, but I'll be free again soon!

**Comment by kirinelf** [comment]
I hate to ask so much, but both a /needbutpass and a /greedbutpass would be great, and failing that a /needbutpass on its own would be lovely! 

...Actually now that I'm looking at the commands again, I wonder if I could've just done a /need then a /pass macro. That would probably have saved us all a lot of time. >_> <_< >_> >_<

I'm about to go on another hiatus myself, going out of the country for a bit, so no need to hurry on my account! 

Curious about the state of PSO2. I saw Ina giving it a go a while back, and I think Fubuki plays it quite a bit, but no idea what the state of both the original and the... reboot? New Genesis or something? is. Hope everything's going okay on that front!
